import { Dimensions, StyleSheet } from "react-native";

const { height, width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  pickerContainer: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 50,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#333",
  },
  subtitle: {
    fontSize: 16,
    color: "#666",
    marginBottom: 30,
    textAlign: "center",
  },
  pickButton: {
    backgroundColor: "#2196F3",
    paddingHorizontal: 40,
    paddingVertical: 15,
    borderRadius: 10,
  },
  pickButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 10,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    zIndex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
  },
  headerButton: {
    color: "#2196F3",
    fontSize: 16,
    fontWeight: "600",
  },
  canvas: {
    backgroundColor: "#e0e0e0",
  },
  floorPlanImage: {
    width: height,
    height: width,
  },
  marker: {
    position: "absolute",
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    transformOrigin: "center",
  },
  markerCount: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: "#2196F3",
    color: "#fff",
    fontSize: 10,
    fontWeight: "bold",
    width: 18,
    height: 18,
    borderRadius: 9,
    textAlign: "center",
    lineHeight: 18,
    overflow: "hidden",
  },
  popup: {
    position: "absolute",
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 10,
    width: 180,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 100,
  },
  popupButton: {
    padding: 10,
    backgroundColor: "#4CAF50",
    borderRadius: 8,
    marginBottom: 8,
  },
  popupText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: "600",
    fontSize: 13,
  },
  popupCancel: {
    padding: 8,
  },
  popupCancelText: {
    color: "#666",
    textAlign: "center",
    fontSize: 12,
  },
  popupArrow: {
    position: "absolute",
    bottom: -10,
    left: "50%",
    marginLeft: -10,
    width: 0,
    height: 0,
    borderLeftWidth: 20,
    borderRightWidth: 20,
    borderTopWidth: 20,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderTopColor: "#fff",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  optionsModal: {
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 20,
    width: 280,
  },
  optionsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 15,
  },
  optionButton: {
    backgroundColor: "#2196F3",
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
  },
  optionText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: "600",
    fontSize: 15,
  },
  optionCancelButton: {
    padding: 15,
  },
  optionCancelText: {
    color: "#666",
    textAlign: "center",
    fontSize: 15,
  },
  photosModal: {
    flex: 1,
    backgroundColor: "#fff",
    marginTop: 50,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  photosHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  photosTitle: {
    fontSize: 18,
    fontWeight: "bold",
  },
  closeButton: {
    color: "#2196F3",
    fontSize: 16,
    fontWeight: "600",
  },
  photosGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    padding: 10,
  },
  photoContainer: {
    width: (width - 40) / 3,
    height: (width - 40) / 3,
    margin: 5,
    position: "relative",
  },
  photoThumbnail: {
    width: "100%",
    height: "100%",
    borderRadius: 10,
  },
  deleteButton: {
    position: "absolute",
    top: 5,
    right: 5,
    backgroundColor: "rgba(255,0,0,0.8)",
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  deleteButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 12,
  },
  instructions: {
    position: "absolute",
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: "center",
    color: "#666",
    fontSize: 14,
    backgroundColor: "rgba(255,255,255,0.8)",
    paddingVertical: 8,
  },

  fullscreenOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#fff",
    zIndex: 5,
  },

  showListButton: {
    position: "absolute",
    bottom: 40,
    right: 20,
    backgroundColor: "#2196F3",
    padding: 12,
    borderRadius: 10,
    zIndex: 10,
    elevation: 10,
  },
});
